[Options]
Version=7
Query=Biz.Ref.ResourceTag
HierarchicalField=Name
CanEdit=0
Hierarchical=1
OnMove=картотека_ПриПеремещении
OnEdit=картотека_ПриРедактировании
OnPost=картотека_ПриЗаписи
OnCancel=картотека_ПриОтмене
OnBeforeModify=картотека_ПередИзменением
OnModify=картотека_ПриИзменении
CanInplace=1
ColumnCount=2
Column:0=Code
Column:1=Name
TreeVisible=1
TreeWidth=120
SubTableWidth=100
SubTableHeight=1

[.Column.Code]
Caption=Код
Width=132

[.Column.Name]
Caption=Имя
Width=0
ColumnFormat=1
