const ru = {
    calendar: {
	monthShort: ["Янв", "Февр", "Март", "Апр", "Май", "Июнь", "Июль", "Авг", "Сент", "Окт", "Нояб", "Дек"],
	monthFull: ["Январь", "Февраль", "Март", "Апрель", "Май", "Июнь", "Июль", "Август", "Сентябрь", "Октябрь", "Ноябрь", "Декабрь"],
	dayShort:["Вс", "Пн", "Вт", "Ср", "Чт", "Пт", "Сб"],
	dayFull: ["Воскресенье", "Понедельник", "Вторник", "Среда", "Четверг", "Пятница", "Суббота"],
	clear: "Очистить",
	done: "Выполнено",
	today: "Сегодня",
    },
    todo: {
	// Toolbar
		"No project": "Без проекта",
		"Search project": "Поиск проекта",
		"Add project": "Добавить проект",
		"Rename project": "Переименовать проект",
		"Delete project": "Удалить проект",
	"Completed tasks": "Выполненные пункты",
		Show: "Показать",
		Hide: "Скрыть",
		"Sort by": "Сортировка по",
		"Text (a-z)": "Текст (а-я)",
		"Text (z-a)": "Текст (я-а)",
		"Due date (new to old)": "Крайний срок (сначала новые)",
		"Due date (old to new)": "Крайний срок (сначала старые)",
		"Completion date (new to old)": "Дата выполнения (сначала новые)",
		"Completion date (old to new)": "Дата выполнения (сначала старые)",
		"Created (new to old)": "Дата создания (сначала новые)",
		"Created (old to new)": "Дата создания (сначала старые)",
		"Edited (new to old)": "Дата редактирования (сначала новые)",
		"Edited (old to new)": "Дата редактирования (сначала старые)",
	// Task
		"Add task below": "Добавить пункт ниже",
		"Add subtask": "Добавить подпункт",
		"Set due date": "Установить дату",
		Indent: "Абзац",
		Unindent: "Без абзаца",
		"Assign to": "Назначить",
		"Move to": "Сдвинуть",
		"Set priority": "Приоритет",
		"Reset priority": "Сброс",
		High: "Высокий",
		Medium: "Средний",
		Low: "Низкий",
		Duplicate: "Дублировать",
		Copy: "Скопировать",
		Paste: "Вставить",
		Delete: "Удалить",
	// Shortcut
		Enter: "Enter",
		Tab: "Tab",
		"Shift+Tab": "Shift+Tab",
		"Ctrl+D": "Ctrl+D",
		"Ctrl+C": "Ctrl+C",
		"Ctrl+V": "Ctrl+V",
		// For Mac OS
		"CMD+D": "CMD+D",
		"CMD+C": "CMD+C",
		"CMD+V": "CMD+V",
	// Editor
	"Type what you want": "Введите текст",
	// Other
		Search: "Suche",
		"Add task": "Добавить пункт",
		"New project": "Новый проект",
    },
};