[Options]
Version=7
Query=Bas.Base.Basic
Hierarchical=1
OnOpenBlank=картотека_ПриОткрытииБланка
OnCreateRecord=картотека_ПриСозданииЗаписи
OnBeforeModify=картотека_ПередИзменением
OnModify=картотека_ПриИзменении
ShowCount=0
CanCopy=1
OnClick=картотека_ПриНажатии
ColumnCount=0
TreeVisible=1
TreeWidth=190
SubTableWidth=0
SubTableHeight=1
SubTableAlign=0
CanResizeTemplate=1
