[Options]
Version=7
Query=.Config.Ini
Hierarchical=1
OnMove=картотека_ПриПеремещении
OnOpenBlank=картотека_ПриОткрытииБланка
OnClick=картотека_ПриНажатии
OnRearrange=картотека_ПриОформлении
ColumnCount=1
Column:0=DocID
TreeVisible=1
TreeWidth=120
SubTableWidth=0
SubTableHeight=0
SubTableAlign=0

[.Column.DocID]
Caption=DocID
Width=100
Editable=0
Alignment=1
ColumnFormat=2
